"
I am an utility class used for finding the filesystem location of a cloned iceberg repository that corresponds to a specific class.

I am to be used to facilitate storing data assets in git repositories.

This class is provided for backward compatibility purposes. You should use PhaNAPIGitProjectAssets instead.
"
Class {
	#name : #PhaNAPIIcebergProjectAssets,
	#superclass : #PhaNAPIGitProjectAssets,
	#category : #'PhaNAPI-Iceberg'
}
